Repository aragon/aragon-cli, pull requests merged in 2018-08, with the labels that each got.

#161 Bump ganache-core version to ensure ethereumjs-wallet is pinned to 0.6.0
  package-lock.json
  package.json
Labels: epic: in sprint addition, sprint: 0.5.4

#144 Always generate artifact if there is a contract linked in the arapp file
  src/commands/apm_cmds/publish.js
Labels: enhancement, epic: dev tooling, epic: in sprint addition, sprint: 0.5.2

#145 Pass contract name specified in publish to deploy
  src/cli.js
  src/commands/apm_cmds/publish.js
  src/commands/run.js
Labels: epic: dev tooling, epic: in sprint addition, sprint: 0.5.2

#176 fix(commands/apm/grant): use updated CREATE_VERSION_ROLE hash
  src/acl/index.js
  src/commands/apm_cmds/grant.js
  src/commands/apm_cmds/publish.js
Labels: external contribution
