Repository aragon/aragon-cli, pull requests merged in 2019-07, with the labels that each got.

#571 New prepublish option for apm publish
  docs/Apm-commands.md
  docs/Main-commands.md
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/src/util.js
  packages/e2e-tests/src/cli/run.test.js.md
  packages/e2e-tests/src/cli/run.test.js.snap
Labels: cmd: apm publish, 💡 feature update

#570 Refactor artifact generation & improve sanity check
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
Labels: cmd: apm publish, 💡 feature update

#528 Make go-ipfs optional
  docs-internal/Specification.md
  package.json
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/ipfs_cmds/install.js
  packages/aragon-cli/src/commands/ipfs_cmds/status.js
  packages/aragon-cli/src/commands/ipfs_cmds/uninstall.js
  packages/aragon-cli/src/helpers/ipfs-daemon.js
  packages/aragon-cli/src/helpers/truffle-runner.js
  packages/aragon-cli/src/lib/ipfs/index.js
  packages/aragon-cli/src/util.js
  packages/aragon-cli/test/lib/ipfs.test.js
  packages/aragon-cli/test/util.test.js
  packages/e2e-tests/README.md
  packages/e2e-tests/package.json
  packages/e2e-tests/src/cli/ipfs.posttest.js
  packages/e2e-tests/src/cli/ipfs.pretest.js
  packages/e2e-tests/src/cli/ipfs.pretest.js.md
  packages/e2e-tests/src/cli/ipfs.pretest.js.snap
  packages/e2e-tests/src/cli/run.test.js
  packages/e2e-tests/src/cli/run.test.js.md
  packages/e2e-tests/src/cli/run.test.js.snap
  packages/e2e-tests/src/create-aragon-app/index.posttest.js
Labels: 💡 feature update, 🚀 new feature

#574 Output publish information before publishing
  README.md
  docs/Apm-commands.md
  docs/Main-commands.md
  packages/aragon-cli/README.md
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/commands/ipfs_cmds/propagate.js
  packages/aragon-cli/src/commands/ipfs_cmds/view.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/src/util.js
  packages/e2e-tests/package.json
  packages/e2e-tests/src/cli/apm-publish.test.js
  packages/e2e-tests/src/cli/run.test.js.md
  packages/e2e-tests/src/cli/run.test.js.snap
Labels: cmd: apm publish, 💡 feature update

#504 Update aragonCLI Roadmap
  CONTRIBUTING.md
  docs-internal/Roadmap.md
Labels: 💬 needs discussion

#590 v6.0.1
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/dao_cmds/acl.js
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
Labels: 🛠️ maintenance

#589 Update CHANGELOG.md
  CHANGELOG.md
Labels: 🛠️ maintenance

#591 Update lockfiles
  docs-internal/Dependencies.md
  package.json
  packages/aragon-cli/npm-shrinkwrap.json
  packages/create-aragon-app/npm-shrinkwrap.json
Labels: 🛠️ maintenance

#628 Update changelogs & readmes
  CHANGELOG.md
  CHANGELOG_STABLE_VERSIONS.md
  README.md
  packages/aragon-cli/README.md
Labels: 🛠️ maintenance

#625 Add gas-price global option
  packages/aragon-cli/config/truffle.default.js
  packages/aragon-cli/package.json
  packages/aragon-cli/src/acl/index.js
  packages/aragon-cli/src/cli.js
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/create.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/grant.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/remove-manager.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/revoke.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/set-manager.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/utils/aclExecHandler.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/change-controller.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/aragonjs-wrapper.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/dao_cmds/utils/knownApps.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/commands/ipfs_cmds/install.js
  packages/aragon-cli/src/commands/run.js
  packages/e2e-tests/src/cli/help.test.js.md
  packages/e2e-tests/src/cli/help.test.js.snap
Labels: 💡 feature update

#646 Use all environment on artifact generation
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
Labels: cmd: apm publish, 💡 feature update

#652 Refactor cli-utils package
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/apm_cmds/info.js
  packages/aragon-cli/src/commands/apm_cmds/packages.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/versions.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/change-controller.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/commands/init.js
  packages/aragon-cli/src/commands/ipfs_cmds/install.js
  packages/aragon-cli/src/commands/ipfs_cmds/propagate.js
  packages/aragon-cli/src/commands/ipfs_cmds/start.js
  packages/aragon-cli/src/commands/ipfs_cmds/status.js
  packages/aragon-cli/src/commands/ipfs_cmds/uninstall.js
  packages/aragon-cli/src/commands/ipfs_cmds/view.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/test/commands/init.test.js
  packages/cli-utils/npm-shrinkwrap.json
  packages/cli-utils/package.json
  packages/cli-utils/src/helpers/default-apm.js
  packages/cli-utils/src/helpers/listr-options.js
  packages/cli-utils/src/helpers/web3-fallback.js
  packages/cli-utils/src/reporters/ListrRenderer.js
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
  packages/create-aragon-app/src/cli.js
  packages/create-aragon-app/src/commands/create-aragon-app.js
  packages/create-aragon-app/src/helpers/default-apm.js
  packages/create-aragon-app/src/helpers/listr-options.js
  packages/create-aragon-app/src/reporters/ConsoleReporter.js
  packages/create-aragon-app/src/reporters/ListrRenderer.js
  packages/create-aragon-app/test/create-aragon-app.test.js
  packages/e2e-tests/npm-shrinkwrap.json
  packages/e2e-tests/src/create-aragon-app/index.pretest.js.md
  packages/e2e-tests/src/create-aragon-app/index.pretest.js.snap
Labels: 🛠️ maintenance

#654 Fix fetch repo option when publishing only content
  packages/aragon-cli/src/commands/apm_cmds/publish.js
Labels: cmd: apm publish, 🐛 bug

#657 Small cleanup
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/scripts/extract-roles.js
  packages/cli-utils/npm-shrinkwrap.json
  packages/cli-utils/package.json
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
  packages/create-aragon-app/src/cli.js
  packages/create-aragon-app/src/commands/create-aragon-app.js
  packages/create-aragon-app/src/helpers/default-apm.js
  packages/create-aragon-app/src/helpers/listr-options.js
  packages/create-aragon-app/src/reporters/ConsoleReporter.js
  packages/create-aragon-app/src/reporters/ListrRenderer.js
  packages/create-aragon-app/test/create-aragon-app.test.js
  packages/e2e-tests/npm-shrinkwrap.json
Labels: 🛠️ maintenance

#660 Fix prepare files function to handle --files correctly
  packages/aragon-cli/config/truffle.default.js
  packages/aragon-cli/scripts/extract-roles.js
  packages/aragon-cli/src/commands/apm_cmds/extract-functions.js
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/commands/apm_cmds/util/preprare-files.js
  packages/aragon-cli/src/commands/apm_cmds/versions.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/change-controller.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/dao_cmds/utils/knownApps.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/src/commands/start.js
  packages/e2e-tests/src/cli/run.test.js.md
  packages/e2e-tests/src/cli/run.test.js.snap
Labels: cmd: apm publish, 🐛 bug, 💡 feature update

#666 Fix decorateWithAbi function to filter by function type
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
Labels: 🐛 bug

#668 Add isPortTaken function to utils
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/apm_cmds/info.js
  packages/aragon-cli/src/commands/apm_cmds/packages.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/versions.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/change-controller.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/helpers/web3-fallback.js
  packages/cli-utils/npm-shrinkwrap.json
  packages/cli-utils/package.json
  packages/cli-utils/src/util.js
Labels: 🛠️ maintenance
