Repository aragon/aragon-cli, pull requests merged in 2019-06, with the labels that each got.

#507 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📚 docs

#455 Handle Aragon gateway on environment middleware
  packages/aragon-cli/src/middleware/environment.js
Labels: 🚀 enhancement

#510 Update to yargs 13
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/cli.js
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
  packages/create-aragon-app/src/cli.js
  packages/e2e-tests/npm-shrinkwrap.json
Labels: 🚀 enhancement

#516 Remove lockfile for e2e tests
  package.json
  packages/e2e-tests/npm-shrinkwrap.json
Labels: 🐛 bug

#508 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📚 docs

#525 Update apm docs
  docs/Global-confg.md
  docs/Intro.md
Labels: 📚 docs

#523 Add CHANGELOG.md & Update README.md
  .github/release-drafter.yml
  CHANGELOG.md
  README.md
  docs-internal/Continuous-integration.md
  docs-internal/Labels.md
  docs-internal/Releasing.md
  packages/aragon-cli/README.md
Labels: 🛠️ maintenance

#526 Update dependencies
  .github/release-drafter.yml
  .travis.yml
  CHANGELOG.md
  docs-internal/Dependencies.md
  greenkeeper.json
  packages/aragon-cli/package-lock.json
  packages/aragon-cli/package.json
  packages/create-aragon-app/package-lock.json
Labels: 🛠️ maintenance

#426 Sanity check artifacts in apm publish
  packages/aragon-cli/src/commands/apm.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/commands/apm_cmds/util/preprare-files.js
  packages/aragon-cli/src/commands/dao_cmds/utils/getRepoTask.js
  packages/aragon-cli/src/commands/run.js
  packages/e2e-tests/src/cli/apm-publish.test.js
  packages/e2e-tests/src/cli/apm-publish.test.js.md
  packages/e2e-tests/src/cli/apm-publish.test.js.snap
  packages/e2e-tests/src/cli/help.test.js.md
  packages/e2e-tests/src/cli/help.test.js.snap
  packages/e2e-tests/src/cli/run.test.js
  packages/e2e-tests/src/util.js
Labels: 🚀 new feature, 🦅 flock/nest high priority

#543 Include documentation about links
  docs/Global-confg.md
Labels: 📚 docs

#550 Fix lockfiles
  CHANGELOG.md
  packages/aragon-cli/npm-shrinkwrap.json
  packages/create-aragon-app/npm-shrinkwrap.json
Labels: 🛠️ maintenance

#545 Fix e2e test setup
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/e2e-tests/README.md
  packages/e2e-tests/package-lock.json
  packages/e2e-tests/package.json
  packages/e2e-tests/src/cli/apm-publish.test.js
  packages/e2e-tests/src/cli/apm-publish.test.js.md
  packages/e2e-tests/src/cli/apm-publish.test.js.snap
  packages/e2e-tests/src/cli/devchain.posttest.js
  packages/e2e-tests/src/cli/devchain.pretest.js
  packages/e2e-tests/src/cli/devchain.pretest.js.md
  packages/e2e-tests/src/cli/devchain.pretest.js.snap
  packages/e2e-tests/src/cli/ipfs.posttest.js
  packages/e2e-tests/src/cli/ipfs.pretest.js
  packages/e2e-tests/src/cli/ipfs.pretest.js.md
  packages/e2e-tests/src/cli/ipfs.pretest.js.snap
  packages/e2e-tests/src/cli/run.test.js
  packages/e2e-tests/src/cli/run.test.js.md
  packages/e2e-tests/src/cli/run.test.js.snap
  packages/e2e-tests/src/create-aragon-app/index.posttest.js
  packages/e2e-tests/src/create-aragon-app/index.pretest.js
  packages/e2e-tests/src/create-aragon-app/index.pretest.js.md
  packages/e2e-tests/src/create-aragon-app/index.pretest.js.snap
  packages/e2e-tests/src/create-aragon-app/index.test.js
  packages/e2e-tests/src/util.js
Labels: 🛠️ maintenance

#562 Add appveyor.yml to prevent CI fail
  appveyor.yml
Labels: 🛠️ maintenance

#567 Pass apm opts to @aragon/wrapper
  appveyor.yml
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
Labels: 💡 feature update

#568 Delete dev lockfiles
  .gitignore
  docs-internal/Continuous-integration.md
  greenkeeper.json
  package-lock.json
  package.json
  packages/aragon-cli/package.json
  packages/create-aragon-app/package.json
  packages/e2e-tests/package-lock.json
Labels: 🛠️ maintenance

#555 Update dao token new options
  docs/Dao-commands.md
  packages/aragon-cli/src/cli.js
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/exec.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/util.js
Labels: cmd: dao act, cmd: dao exec, cmd: dao token new, 🐛 bug, 💡 feature update
