Repository aragon/aragon-cli, pull requests merged in 2019-08, with the labels that each got.

#674 Update command to not hang after finishing
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/ipfs_cmds/propagate.js
  packages/aragon-cli/src/commands/ipfs_cmds/start.js
  packages/aragon-cli/src/commands/run.js
  packages/e2e-tests/src/cli/devchain.pretest.js.md
  packages/e2e-tests/src/cli/devchain.pretest.js.snap
  packages/e2e-tests/src/cli/run.test.js.md
  packages/e2e-tests/src/cli/run.test.js.snap
Labels: cmd: apm publish, cmd: ipfs propagate, cmd: run, 🐛 bug

#678 New command devchain status
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/scripts/extract-roles.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/devchain.js
  packages/aragon-cli/src/commands/devchain_cmds/start.js
  packages/aragon-cli/src/commands/devchain_cmds/status.js
  packages/aragon-cli/src/commands/run.js
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/e2e-tests/npm-shrinkwrap.json
  packages/e2e-tests/src/cli/help.test.js.md
  packages/e2e-tests/src/cli/help.test.js.snap
  packages/e2e-tests/src/cli/run.test.js.md
  packages/e2e-tests/src/cli/run.test.js.snap
Labels: cmd: devchain, 🚀 new feature

#681 Update README & CHANGELOG files
  CHANGELOG.md
  CHANGELOG_STABLE_VERSIONS.md
  README.md
  packages/aragon-cli/README.md
Labels: 📚 docs, 🛠️ maintenance

#685 Fix prepare publish function and publish intent argument
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/preprare-files.js
  packages/aragon-cli/src/commands/run.js
Labels: cmd: apm publish, 🐛 bug

#686 Update aragen & client
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/run.js
Labels: cmd: run, 💡 feature update

#492 Iterate dao act
  packages/aragon-cli/src/commands/dao_cmds/act.js
Labels: cmd: dao act, 🚀 new feature

#696 Handle IPFS not being installed
  packages/aragon-cli/src/commands/ipfs_cmds/start.js
  packages/aragon-cli/src/helpers/ipfs-daemon.js
Labels: 🐛 bug

#697 Update documentation
  docs/Apm-commands.md
  docs/Dao-commands.md
  docs/Global-confg.md
  docs/Intro.md
  docs/Main-commands.md
  packages/aragon-cli/package.json
Labels: 📚 docs

#698 Update changelog
  CHANGELOG.md
  CHANGELOG_STABLE_VERSIONS.md
  README.md
  packages/aragon-cli/README.md
  packages/e2e-tests/src/cli/help.test.js.md
  packages/e2e-tests/src/cli/help.test.js.snap
Labels: 📚 docs, 🛠️ maintenance

#699 Doc: Improve IPFS section
  docs/Intro.md
Labels: 📚 docs

#701 Fix http publish workflow && improve ipfs handler
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/utils/aclExecHandler.js
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/exec.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
Labels: cmd: apm publish, 🐛 bug, 💡 feature update

#541 Refactor: Remove init command & network option. Clean apm
  packages/aragon-cli/package.json
  packages/aragon-cli/src/cli.js
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/apm_cmds/info.js
  packages/aragon-cli/src/commands/apm_cmds/packages.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/version.js
  packages/aragon-cli/src/commands/apm_cmds/versions.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/commands/init.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/src/lib/init/check-project-exists.js
  packages/aragon-cli/src/lib/init/index.js
  packages/aragon-cli/src/lib/init/prepare-template.js
  packages/aragon-cli/src/middleware/environment.js
  packages/aragon-cli/test/commands/init.test.js
Labels: 💥 breaking change

#713 Add Aragon's default endpoint
  packages/aragon-cli/src/middleware/environment.js
Labels: 🐛 bug

#720 Release patch version
  README.md
  packages/aragon-cli/README.md
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/cli.js
  packages/cli-utils/npm-shrinkwrap.json
  packages/cli-utils/package.json
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
  packages/e2e-tests/npm-shrinkwrap.json
  packages/e2e-tests/src/cli/devchain.pretest.js.md
  packages/e2e-tests/src/cli/devchain.pretest.js.snap
  packages/e2e-tests/src/cli/help.test.js.md
  packages/e2e-tests/src/cli/help.test.js.snap
Labels: 🛠️ maintenance

#724 Fix README.md
  README.md
  packages/aragon-cli/README.md
Labels: 🛠️ maintenance

#733 Small fixes
  docs/Dao-commands.md
  packages/aragon-cli/config/environments.default.json
  packages/aragon-cli/config/truffle.default.js
  packages/aragon-cli/package.json
  packages/aragon-cli/scripts/extract-roles.js
  packages/aragon-cli/src/cli.js
Labels: 💡 feature update

#738 Include mention about new array syntax for app-init-args
  docs/Main-commands.md
Labels: 📚 docs

#739 Remove deprecated react-kit boilerplate
  packages/create-aragon-app/README.md
Labels: 📚 docs

#745 Rollback to truffle-config v4
  packages/aragon-cli/config/truffle.default.js
Labels: 🛠️ maintenance
