Repository aragon/aragon-cli, pull requests merged in 2019-12, with the labels that each got.

#972 Extract logic for "token change-controller" command
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/change-controller.js
  packages/aragon-cli/src/lib/token.js
  packages/aragon-cli/test/integration/token.test.js
Labels: SDK v7

#946 Refactor deprecated code
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/version.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/dao_cmds/utils/old-bare-template-abi.js
  packages/aragon-cli/src/commands/init.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/src/lib/init/check-project-exists.js
  packages/aragon-cli/src/lib/init/index.js
  packages/aragon-cli/src/lib/init/prepare-template.js
  packages/aragon-cli/test/commands/init.test.js
Labels: SDK v7

#970 Extract logic from "dao act"
  docs/Dao-commands.md
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/exec.js
  packages/aragon-cli/src/commands/dao_cmds/utils/app-kernel.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/lib/dao/encodeActCall.js
  packages/aragon-cli/src/lib/dao/exec.js
  packages/aragon-cli/src/lib/getAppKernel.js
  packages/aragon-cli/test/integration/acl.test.js
  packages/aragon-cli/test/lib/dao/encodeActCall.test.js
  packages/aragon-cli/test/lib/getAppKernel.test.js
  packages/aragon-cli/test/mocks.js
Labels: SDK v7

#955 Extract logic from "dao apps" and "dao new"
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/utils/daoArg.js
  packages/aragon-cli/src/lib/dao/apps.js
  packages/aragon-cli/src/lib/dao/bare-template-abi.js
  packages/aragon-cli/src/lib/dao/new.js
  packages/aragon-cli/test/integration/acl.test.js
  packages/aragon-cli/test/integration/dao/apps.test.js
  packages/aragon-cli/test/integration/dao/new.test.js
  packages/aragon-cli/test/util.test.js
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/e2e-tests/src/cli/dao-new.test.js
Labels: SDK v7

#874 Extracts logic from dao commands
  .github/workflows/continuous-integration.yml
  .travis.yml
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/lib/dao/exec.js
  packages/aragon-cli/src/lib/dao/kernel.js
  packages/aragon-cli/src/lib/dao/utils.js
  packages/aragon-cli/test/lib/dao/kernel.test.js
  packages/cli-utils/npm-shrinkwrap.json
Labels: SDK v7

#951 Refactor IPFS cmds
  .github/workflows/continuous-integration.yml
  .travis.yml
  package.json
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/scripts/setup-integration-tests.js
  packages/aragon-cli/scripts/teardown-integration-tests.js
  packages/aragon-cli/src/cli.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/utils/aclExecHandler.js
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/commands/dao_cmds/exec.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/ipfs_cmds/install.js
  packages/aragon-cli/src/commands/ipfs_cmds/propagate.js
  packages/aragon-cli/src/commands/ipfs_cmds/start.js
  packages/aragon-cli/src/commands/ipfs_cmds/status.js
  packages/aragon-cli/src/commands/ipfs_cmds/stop.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/src/index.js
  packages/aragon-cli/src/lib/dao/exec.js
  packages/aragon-cli/src/lib/ipfs/aragon.js
  packages/aragon-cli/src/lib/ipfs/config.js
  packages/aragon-cli/src/lib/ipfs/constants.js
  packages/aragon-cli/src/lib/ipfs/daemon.js
  packages/aragon-cli/src/lib/ipfs/data.js
  packages/aragon-cli/src/lib/ipfs/index.js
  packages/aragon-cli/src/lib/ipfs/install.js
  packages/aragon-cli/src/lib/ipfs/misc.js
  packages/aragon-cli/src/lib/ipfs/propagation.js
  packages/aragon-cli/src/lib/node/index.js
  packages/aragon-cli/src/lib/node/misc.js
  packages/aragon-cli/src/lib/node/packages.js
  packages/aragon-cli/src/lib/node/process.js
  packages/aragon-cli/test/integration/acl.test.js
  packages/aragon-cli/test/integration/ipfs/daemonAndConfig.test.js
  packages/aragon-cli/test/integration/ipfs/data.test.js
  packages/aragon-cli/test/integration/ipfs/propagation.test.js
  packages/aragon-cli/test/integration/ipfs/snapshots/daemonAndConfig.test.js.md
  packages/aragon-cli/test/integration/ipfs/snapshots/daemonAndConfig.test.js.snap
  packages/aragon-cli/test/integration/ipfs/snapshots/data.test.js.md
  packages/aragon-cli/test/integration/ipfs/snapshots/data.test.js.snap
  packages/cli-utils/npm-shrinkwrap.json
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
  packages/create-aragon-app/src/cli.js
  packages/create-aragon-app/src/index.js
  packages/e2e-tests/npm-shrinkwrap.json
Labels: SDK v7

#968 v6.4.2
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/e2e-tests/src/cli/help.test.js
  packages/e2e-tests/src/cli/version.test.js
Labels: 🛠️ maintenance

#990 Update shrinkwraps
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
Labels: 🛠️ maintenance

#991 Regenerate shrinkwraps
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/e2e-tests/npm-shrinkwrap.json
Labels: 🛠️ maintenance

#993 Adds a test for the Custom Deploy guide
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/test/dao/new.test.js
  packages/aragon-cli/test/guides/customDeploy.test.js
  packages/aragon-cli/test/utils.js
  packages/toolkit/package.json
Labels: SDK v7

#1006 Move e2e tests to aragon-cli
  packages/aragon-cli/package.json
  packages/aragon-cli/test/acl/snapshots/acl.test.js.md
  packages/aragon-cli/test/acl/snapshots/acl.test.js.snap
  packages/aragon-cli/test/dao/dao-id-assign.test.js
  packages/aragon-cli/test/dao/dao-new.test.js
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.md
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.snap
  packages/aragon-cli/test/help/help.test.js
  packages/aragon-cli/test/help/snapshots/help.test.js.md
  packages/aragon-cli/test/help/snapshots/help.test.js.snap
  packages/aragon-cli/test/utils.js
  packages/aragon-cli/test/version/snapshots/version.test.js.md
  packages/aragon-cli/test/version/snapshots/version.test.js.snap
  packages/aragon-cli/test/version/version.test.js
  packages/e2e-tests/src/cli/dao-id-assign.test.js
  packages/e2e-tests/src/cli/dao-new.test.js
  packages/e2e-tests/src/cli/dao-new.test.js.md
  packages/e2e-tests/src/cli/dao-new.test.js.snap
  packages/e2e-tests/src/cli/help.test.js
  packages/e2e-tests/src/cli/help.test.js.md
  packages/e2e-tests/src/cli/help.test.js.snap
  packages/e2e-tests/src/cli/version.test.js
  packages/e2e-tests/src/cli/version.test.js.md
  packages/e2e-tests/src/cli/version.test.js.snap
  packages/toolkit/package.json
  packages/toolkit/src/dao/new.js
  packages/toolkit/src/helpers/default-apm.js
  packages/toolkit/test/acl/acl.test.js
  packages/toolkit/test/acl/snapshots/acl.test.js.md
  packages/toolkit/test/acl/snapshots/acl.test.js.snap
  packages/toolkit/test/dao/apps.test.js
  packages/toolkit/test/dao/new.test.js
  packages/toolkit/test/test-helpers/getLocalWeb3.js
  packages/toolkit/test/test-helpers/getNewDaoAddress.js
  packages/toolkit/test/test-helpers/index.js
  packages/toolkit/test/test-helpers/isAddress.js
Labels: SDK v7

#1019 Fixing global option detection removing yargs strict
  packages/aragon-cli/src/cli.js
Labels: 🐛 bug

#1018 Unskip tests
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/start.js
  packages/aragon-cli/test/dao/dao-new.test.js
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.md
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.snap
  packages/aragon-cli/test/help/snapshots/help.test.js.md
  packages/aragon-cli/test/help/snapshots/help.test.js.snap
  packages/aragon-cli/test/start/start.test.js
  packages/toolkit/src/dao/new.js
Labels: SDK v7

#1025 Fixes homedir paths in snapshots
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.md
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.snap
  packages/aragon-cli/test/utils.js
Labels: SDK v7

#992 Remove or replace process.exit()
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/cli.js
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/apm_cmds/info.js
  packages/aragon-cli/src/commands/apm_cmds/packages.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/versions.js
  packages/aragon-cli/src/commands/contracts.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/commands/dao_cmds/act.js
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/commands/dao_cmds/exec.js
  packages/aragon-cli/src/commands/dao_cmds/id-assign.js
  packages/aragon-cli/src/commands/dao_cmds/install.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/change-controller.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/upgrade.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/commands/extract-functions.js
  packages/aragon-cli/src/commands/ipfs_cmds/install.js
  packages/aragon-cli/src/commands/ipfs_cmds/uninstall.js
  packages/aragon-cli/src/commands/run.js
  packages/aragon-cli/src/helpers/truffle-runner.js
  packages/aragon-cli/src/util.js
  packages/toolkit/src/acl/view.js
Labels: SDK v7

#1030 Removed usage of snapshots in dao new tests
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/test/dao/dao-new.test.js
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.md
  packages/aragon-cli/test/dao/snapshots/dao-new.test.js.snap
Labels: SDK v7

#1020 Fix e2e-tests and add new cases && move to create-aragon-app
  package.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/cli.js
  packages/aragon-cli/src/toolkit.js
  packages/create-aragon-app/README.md
  packages/create-aragon-app/aliases/create-aragon-app
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
  packages/create-aragon-app/src/cli.js
  packages/create-aragon-app/src/commands/create-aragon-app.js
  packages/create-aragon-app/src/lib/check-project-exists.js
  packages/create-aragon-app/src/lib/prepare-template.js
  packages/create-aragon-app/test/create-app.test.js
  packages/create-aragon-app/test/help.test.js
  packages/create-aragon-app/test/lib.test.js
  packages/create-aragon-app/test/snapshots/version.test.js.md
  packages/create-aragon-app/test/snapshots/version.test.js.snap
  packages/create-aragon-app/test/util.js
  packages/create-aragon-app/test/version.test.js
  packages/e2e-tests/.babelrc
  packages/e2e-tests/README.md
  packages/e2e-tests/npm-shrinkwrap.json
  packages/e2e-tests/package.json
  packages/e2e-tests/src/cli/apm-publish.test.js
  packages/e2e-tests/src/cli/apm-publish.test.js.md
  packages/e2e-tests/src/cli/apm-publish.test.js.snap
  packages/e2e-tests/src/cli/devchain.posttest.js
  packages/e2e-tests/src/cli/devchain.pretest.js
  packages/e2e-tests/src/cli/ipfs.posttest.js
  packages/e2e-tests/src/cli/ipfs.pretest.js
  packages/e2e-tests/src/cli/ipfs.pretest.js.md
  packages/e2e-tests/src/cli/ipfs.pretest.js.snap
  packages/e2e-tests/src/cli/run.test.js
  packages/e2e-tests/src/create-aragon-app/index.posttest.js
  packages/e2e-tests/src/create-aragon-app/index.pretest.js
  packages/e2e-tests/src/create-aragon-app/index.pretest.js.md
  packages/e2e-tests/src/create-aragon-app/index.pretest.js.snap
  packages/e2e-tests/src/create-aragon-app/version.test.js.snap
  packages/toolkit/npm-shrinkwrap.json
  packages/toolkit/package.json
  packages/toolkit/src/index.js
Labels: SDK v7

#1026 Minimize mocking in toolkit tests
  packages/toolkit/src/apm/grantNewVersionsPermission.js
  packages/toolkit/test/apm/getApmRegistryPackages.test.js
  packages/toolkit/test/apm/getApmRepo.test.js
  packages/toolkit/test/apm/getApmRepoVersions.test.js
  packages/toolkit/test/apm/grantNewVersionsPermission.test.js
  packages/toolkit/test/apm/util/acl.test.js
  packages/toolkit/test/apm/util/snapshots/acl.test.js.md
  packages/toolkit/test/apm/util/snapshots/acl.test.js.snap
  packages/toolkit/test/apm/utils.test.js
  packages/toolkit/test/dao/assign-id.test.js
  packages/toolkit/test/dao/new.test.js
  packages/toolkit/test/helpers/aragonjs-wrapper.test.js
  packages/toolkit/test/helpers/snapshots/aragonjs-wrapper.test.js.md
  packages/toolkit/test/helpers/snapshots/aragonjs-wrapper.test.js.snap
  packages/toolkit/test/ipfs/config.test.js
  packages/toolkit/test/ipfs/daemonAndConfig.test.js
  packages/toolkit/test/ipfs/data-viz.test.js
  packages/toolkit/test/ipfs/data.test.js
  packages/toolkit/test/ipfs/propagation.test.js
  packages/toolkit/test/kernel/getAppKernel.test.js
  packages/toolkit/test/mocks.js
  packages/toolkit/test/node/os.test.js
  packages/toolkit/test/test-helpers/getApmOptions.js
  packages/toolkit/test/test-helpers/index.js
  packages/toolkit/test/token/factory.test.js
Labels: SDK v7

#1061 Boilerplates CI and Tests fixes
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/contracts.js
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/commands/start.js
  packages/aragon-cli/src/helpers/truffle-runner.js
  packages/aragon-cli/src/util.js
  packages/aragon-cli/test/dao/dao-id-assign.test.js
  packages/aragon-cli/test/dao/dao-new.test.js
  packages/aragon-cli/test/deploy/deploy.test.js
  packages/aragon-cli/test/environment/loadConfigFiles.test.js
  packages/aragon-cli/test/guides/customDeploy.test.js
  packages/aragon-cli/test/help/help.test.js
  packages/aragon-cli/test/help/snapshots/help.test.js.md
  packages/aragon-cli/test/help/snapshots/help.test.js.snap
  packages/aragon-cli/test/start/start.test.js
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/toolkit/npm-shrinkwrap.json
  packages/toolkit/src/node/process.js
  packages/toolkit/test/acl/params.test.js
  packages/toolkit/test/acl/viewFormatter.test.js
  packages/toolkit/test/apm/getApmRegistryPackages.test.js
  packages/toolkit/test/apm/getApmRepo.test.js
  packages/toolkit/test/apm/getApmRepoVersions.test.js
  packages/toolkit/test/apm/grantNewVersionsPermission.test.js
  packages/toolkit/test/dao/encodeActCall.test.js
  packages/toolkit/test/helpers/contracts/ParseMe.sol
  packages/toolkit/test/helpers/extractContractInfoToFile.test.js
  packages/toolkit/test/ipfs/config.test.js
  packages/toolkit/test/node/os.test.js
  packages/toolkit/test/token/factory.test.js
  packages/toolkit/test/token/token.test.js
Labels: SDK v7
