Repository aragon/aragon-cli, pull requests merged in 2019-11, with the labels that each got.

#865 Refactor deploy - #858 task
  packages/aragon-cli/src/commands/deploy.js
  packages/aragon-cli/src/lib/deploy.js
  packages/aragon-cli/test/lib/deploy.test.js
Labels: SDK v7

#878 Improve build tools usage
  .github/main.workflow
  package.json
  packages/aragon-cli/.babelrc
  packages/aragon-cli/.eslintrc
  packages/aragon-cli/.prettierrc
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/cli.js
  packages/aragon-cli/src/commands/apm_cmds/extract-functions.js
  packages/aragon-cli/src/commands/apm_cmds/publish.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/commands/apm_cmds/version.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/commands/dao_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/change-controller.js
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/dao_cmds/utils/knownApps.js
  packages/aragon-cli/src/helpers/ipfs-daemon.js
  packages/aragon-cli/src/middleware/manifest.js
  packages/aragon-cli/src/middleware/module.js
  packages/aragon-cli/src/util.js
  packages/aragon-cli/test/acl-params.test.js
  packages/aragon-cli/test/helpers/aragonjs-wrapper.test.js
  packages/aragon-cli/test/lib/token.test.js
  packages/cli-utils/npm-shrinkwrap.json
  packages/create-aragon-app/.babelrc
  packages/create-aragon-app/.eslintrc
  packages/create-aragon-app/.prettierrc
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
  packages/create-aragon-app/src/cli.js
  packages/e2e-tests/npm-shrinkwrap.json
Labels: 🛠️ maintenance

#877 Token cmds refactor
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
  packages/aragon-cli/src/lib/token.js
  packages/aragon-cli/test/lib/token.test.js
Labels: SDK v7

#879 Extracts logic from apm commands: info command
  packages/aragon-cli/src/commands/apm_cmds/info.js
  packages/aragon-cli/src/lib/apm/getApmRepo.js
  packages/aragon-cli/test/lib/apm/getApmRepo.test.js
Labels: SDK v7

#898 Review: Extracts logic from apm commands: info command
  packages/aragon-cli/src/commands/apm_cmds/info.js
  packages/aragon-cli/src/lib/apm/getApmRepo.js
  packages/aragon-cli/test/lib/apm/getApmRepo.test.js
Labels: SDK v7, cmd: apm info, 🛠️ maintenance

#915 Update client to 0.8.4
  packages/aragon-cli/package.json
  packages/aragon-cli/src/middleware/environment.js
Labels: 🛠️ maintenance

#916 Use deployed minime factories with optimized code
  packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js
Labels: 🛠️ maintenance

#917 v6.4.0
  lerna.json
  packages/aragon-cli/package.json
  packages/create-aragon-app/package.json
Labels: 🛠️ maintenance

#864 Refactor dao acl - #858 task
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/utils/knownRoles.js
  packages/aragon-cli/src/commands/dao_cmds/acl_cmds/view.js
  packages/aragon-cli/src/lib/acl/typedef.js
  packages/aragon-cli/src/lib/acl/view.js
  packages/aragon-cli/src/lib/acl/viewFormatter.js
  packages/aragon-cli/src/lib/typedef.js
  packages/aragon-cli/test/lib/acl/viewFormatter.test.js
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/create-aragon-app/package.json
Labels: SDK v7

#870 Extracts logic from apm commands: extract-functions command
  packages/aragon-cli/package.json
  packages/aragon-cli/src/commands/apm_cmds/extract-functions.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/helpers/solidity-extractor.js
  packages/aragon-cli/src/lib/apm/extractContractInfoToFile.js
  packages/aragon-cli/test/contracts/ParseMe.sol
  packages/aragon-cli/test/lib/apm/extractContractInfoToFile.test.js
Labels: SDK v7

#875 Refactor dao id assign logic
  packages/aragon-cli/src/commands/dao_cmds/id-assign.js
  packages/aragon-cli/src/lib/dao/assign-id.js
  packages/aragon-cli/src/util.js
  packages/aragon-cli/test/lib/dao/assign-id.test.js
  packages/aragon-cli/test/util.test.js
Labels: SDK v7

#891 Extracts logic from apm commands: versions command
  packages/aragon-cli/src/commands/apm_cmds/versions.js
  packages/aragon-cli/src/lib/apm/getApmRepoVersions.js
  packages/aragon-cli/test/lib/apm/getApmRepoVersions.test.js
Labels: SDK v7

#892 Extracts logic from apm commands: packages command
  packages/aragon-cli/src/commands/apm_cmds/packages.js
  packages/aragon-cli/src/lib/apm/getApmRegistryPackages.js
  packages/aragon-cli/test/lib/apm/getApmRegistryPackages.test.js
Labels: SDK v7

#909 Refactor dao exec logic
  packages/aragon-cli/package.json
  packages/aragon-cli/test/util.test.js
Labels: SDK v7

#910 Refactor dao apps
  packages/aragon-cli/src/commands/dao_cmds/apps.js
  packages/aragon-cli/src/lib/dao/apps.js
Labels: SDK v7

#904 Add integration tests for `dao token new`
  packages/aragon-cli/npm-shrinkwrap.json
  packages/aragon-cli/package.json
  packages/aragon-cli/scripts/setup-integration-tests.js
  packages/aragon-cli/scripts/teardown-integration-tests.js
  packages/aragon-cli/test/integration/snapshots/token.test.js.md
  packages/aragon-cli/test/integration/snapshots/token.test.js.snap
  packages/aragon-cli/test/integration/test-utils.js
  packages/aragon-cli/test/integration/token.test.js
  packages/cli-utils/npm-shrinkwrap.json
  packages/create-aragon-app/npm-shrinkwrap.json
  packages/e2e-tests/npm-shrinkwrap.json
Labels: 🛠️ maintenance

#902 Extracts logic from apm commands: grant command
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/lib/apm/grantNewVersionsPermission.js
  packages/aragon-cli/src/lib/apm/util/acl.js
  packages/aragon-cli/test/lib/apm/grantNewVersionsPermission.test.js
Labels: SDK v7

#871 Extracts logic from apm commands
  packages/aragon-cli/src/commands/apm_cmds/extract-functions.js
  packages/aragon-cli/src/commands/apm_cmds/grant.js
  packages/aragon-cli/src/commands/apm_cmds/info.js
  packages/aragon-cli/src/commands/apm_cmds/packages.js
  packages/aragon-cli/src/commands/apm_cmds/util/generate-artifact.js
  packages/aragon-cli/src/commands/apm_cmds/versions.js
  packages/aragon-cli/src/commands/dao_cmds/utils/execHandler.js
  packages/aragon-cli/src/commands/extract-functions.js
  packages/aragon-cli/src/helpers/solidity-extractor.js
  packages/aragon-cli/src/lib/apm/getApmRegistryPackages.js
  packages/aragon-cli/src/lib/apm/getApmRepo.js
  packages/aragon-cli/src/lib/apm/getApmRepoVersions.js
  packages/aragon-cli/src/lib/apm/grantNewVersionsPermission.js
  packages/aragon-cli/src/lib/apm/util/acl.js
  packages/aragon-cli/src/lib/extractContractInfoToFile.js
  packages/aragon-cli/test/contracts/ParseMe.sol
  packages/aragon-cli/test/lib/apm/extractContractInfoToFile.test.js
  packages/aragon-cli/test/lib/apm/getApmRegistryPackages.test.js
  packages/aragon-cli/test/lib/apm/getApmRepo.test.js
  packages/aragon-cli/test/lib/apm/getApmRepoVersions.test.js
  packages/aragon-cli/test/lib/apm/grantNewVersionsPermission.test.js
Labels: SDK v7
